# Generated by Django 3.2.4 on 2021-06-21 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='dates',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('by_who', models.CharField(max_length=20)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='main.tool')),
            ],
        ),
    ]
